stages:
  data_ingestion:
    cmd: python -m src.kidney_disease_classifier.pipeline.stage_01_data_ingestion
    deps:
      - src/kidney_disease_classifier/pipeline/stage_01_data_ingestion.py
      - configs/configs.yaml
    outs:
      - artifacts/data_ingestion/raw
      - artifacts/data_ingestion/split

  prepare_base_model:
    cmd: python -m src.kidney_disease_classifier.pipeline.stage_02_prepare_base_model
    deps:
      - src/kidney_disease_classifier/pipeline/stage_02_prepare_base_model.py
      - configs/configs.yaml
    params:
      - model.name
      - model.input_shape
      - model.weights
      - training.learning_rate
      - transfer_learning.freeze_all
      - transfer_learning.freeze_till

    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python -m src.kidney_disease_classifier.pipeline.stage_03_model_training
    deps:
      - src/kidney_disease_classifier/pipeline/stage_03_model_training.py
      - configs/configs.yaml
      - artifacts/data_ingestion/split
      - artifacts/prepare_base_model
    params:
      - model
      - training
      - augmentation
      - transfer_learning
      
    outs:
      - artifacts/training


  evaluation:
    cmd: python -m src.kidney_disease_classifier.pipeline.stage_04_model_evaluation
    deps:
      - src/kidney_disease_classifier/pipeline/stage_04_model_evaluation.py
      - configs/configs.yaml
      - artifacts/data_ingestion/split/test
      - artifacts/training
    params:
      - model.name
      - model.input_shape
      - training.batch_size

    metrics:
      - artifacts/evaluation/scores.json
