model:
  name: mobilenetv2              # ["vgg16", "resnet50", "mobilenetv2", "efficientnetb0"]
  input_shape: [224, 224, 3]
  num_classes: 2
  weights: imagenet

training:
  batch_size: 16
  epochs: 10
  learning_rate: 0.0001          # safer for transfer learning
  optimizer: adam

  callbacks:
    early_stopping:
      monitor: val_loss
      patience: 5
      restore_best_weights: true

augmentation:
  enabled: true
  horizontal_flip: true
  rotation: 0.2
  zoom: 0.2
  translation: 0.1

transfer_learning:
  freeze_all: false              # ⚠️ changed (important)
  freeze_till: 20

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1

mlflow:
  experiment_name: kidney_disease_classification