MODEL_TYPE: VGG16 # Available options ["VGG16", "ResNet50", "MobileNetV2", "EfficientNetB0"]
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
